name = "cloudflare-worker-matrix-well-known-1"
compatibility_date = "2023-04-13"
main = "./src/index.ts"
# route = { pattern = "beetlenest.org/.well-known/matrix/*", zone_name = "beetlenest.org" }
minify = true
workers_dev = true

rules = [
    { type = "ESModule", globs = ["src/*.ts"], fallthrough = false }
]

#[build]
#command = "yarn install && yarn run build"
#watch_dir = "src"


[vars]
MATRIX_SERVER_ADDR = "matrix.beetlenest.org:8443"
